CREATE TABLE IF NOT EXISTS study_group (
    id      INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(6)  UNIQUE
);

CREATE TABLE IF NOT EXISTS student (
    id          INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(30) NOT NULL,
    group_id    INT         REFERENCES study_group(id)
);
